sonar.organization=scan-all-with-sonar
sonar.projectKey=ivincetti_tuya-local-wr
sonar.sources=./custom_components/tuya_local
sonar.tests=./tests
sonar.python.coverage.reportPaths=/github/workspace/coverage.xml
sonar.python.version=3
