blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/ivincetti/tuya-local-wr/discussions
    about: Questions and requests for help should be posted in Discussions
